[extension]
name = "kafka"
version = "0.2.0"
type = "resolver"
description = "Map Kafka endpoints to GraphQL fields. Supports publishing and consuming messages."
repository_url = "https://github.com/grafbase/extensions/tree/main/extensions/kafka"
license = "Apache-2.0"

[directives]
resolvers = [ "kafkaPublish", "kafkaSubscription" ]

[permissions]
network = true
