[extension]
name = "postgres"
version = "0.6.0"
description = """
Integrate your Postgres database directly into Grafbase Gateway. This extension exposes your database schema and with the help of the introspection tool, automatically generates a fully-functional GraphQL subgraph, eliminating the need to build and maintain a separate service.
"""
homepage_url = "https://grafbase.com/extensions/postgres"
repository_url = "https://github.com/grafbase/extensions/tree/main/extensions/postgres"
license = "Apache-2.0"
type = "resolver"

# These are the default permissions for the extension.
# The user can enable or disable them as needed in the gateway
# configuration file.
[permissions]
network = true
stdout = true
stderr = true
environment_variables = true

[resolver]
directives = ["pgSelectOne", "pgSelectMany", "pgLookup", "pgInsertOne", "pgInsertMany", "pgUpdateOne", "pgUpdateMany", "pgDeleteOne", "pgDeleteMany"]
