[extension]
name = "postgres"
version = "0.1.0"
description = "A new extension"
homepage_url = "https://grafbase.com/extensions/postgres"
repository_url = "https://github.com/grafbase/extensions/tree/main/extensions/postgres"
license = "Apache-2.0"
type = "selection_set_resolver"

# These are the default permissions for the extension.
# The user can enable or disable them as needed in the gateway
# configuration file.
[permissions]
network = true
stdout = true
stderr = true
environment_variables = true
