[extension]
name = "grpc"
version = "0.1.1"
kind = "resolver"
description = "Integrate the Grafbase Gateway communicate with your gRPC services declaratively."
repository_url = "https://github.com/grafbase/extensions/tree/main/extensions/grpc"
license = "Apache-2.0"

[permissions]
network = true
stdout = false
stderr = false
environment_variables = false

[directives]
definitions = "definitions.graphql"
field_resolvers = ["grpcMethod"]
