[extension]
name = "jwt"
version = "1.3.0"
kind = "authentication"
description = "Restrict access to your graph with JWT"
repository_url = "https://github.com/grafbase/extensions/tree/main/extensions/jwt"
license = "Apache-2.0"

[permissions]
network = true
