[extension]
name = "authenticated"
version = "1.0.1"
kind = "authorization"
description = "Prevent access to elements in the query when the user is not authenticated"
license = "Apache-2.0"
repository_url = "https://github.com/grafbase/extensions/tree/main/extensions/authenticated"
