[extension]
name = "nats"
version = "0.5.1"
kind = "resolver"
description = "Map NATS endpoints to GraphQL fields. Supports regular and JetStream subscriptions, as well as request/reply messaging and the key/value store."
repository_url = "https://github.com/grafbase/extensions/tree/main/extensions/nats"
license = "Apache-2.0"

[resolver]
directives = [
    "natsPublish",
    "natsSubscription",
    "natsRequest",
    "natsKeyValue",
]

[permissions]
network = true
