[package]
name = "sql-ast"
version = "0.1.0"
edition.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
repository.workspace = true

[dependencies]
grafbase-sdk.workspace = true

[lints]
workspace = true
