[extension]
name = "www-authenticate"
version = "0.1.0"
type = "hooks"
description = "Inject the WWW-Authenticate header on 401 responses"
repository_url = "https://github.com/grafbase/extensions/tree/main/extensions/www-authenticate"
license = "Apache-2.0"

# These are the default permissions for the extension.
# The user can enable or disable them as needed in the gateway
# configuration file.
[permissions]
network = false
stdout = false
stderr = false
environment_variables = false
