name: Publish Extensions

on:
  push:
    branches:
      - main

concurrency:
  group: publish-extensions
  cancel-in-progress: false

jobs:
  publish:
    runs-on: depot-ubuntu-24.04-8
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9

      - name: Install Protoc for the gRPC extension
        uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3

      - name: Install Rust
        uses: ./.github/actions/install-rust

      - name: Install Grafbase
        uses: ./.github/actions/install-grafbase

      - name: Build and run publish-extensions
        run: |
          cargo run -p publish-extensions
        env:
          # for publish
          GRAFBASE_ACCESS_TOKEN: ${{ secrets.GRAFBASE_CLI_TOKEN }}
          # for fetching the version
          GRAFBASE_API_TOKEN: ${{ secrets.GRAFBASE_API_TOKEN }}
