name: pull-request

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-pull-request
  cancel-in-progress: true

jobs:
  check-format:
    runs-on: depot-ubuntu-24.04
    env:
      RUSTFLAGS: -D warnings
    steps:
      - name: Get Sources
        uses: actions/checkout@v4

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9

      - name: Install Rust
        uses: ./.github/actions/install-rust
        with:
          components: clippy, rustfmt

      - name: cargo fmt
        shell: bash
        run: |
          cargo fmt --check

      - name: Install Protoc for the gRPC extension
        uses: arduino/setup-protoc@f4d5893b897028ff5739576ea0409746887fa536 # v3

      - name: cargo clippy
        shell: bash
        env:
          RUSTC_WRAPPER: sccache
        run: |
          cargo clippy --locked

      - uses: uncenter/setup-taplo@4f203fdb4f3b1e289c8382cf90d8397d2338df2e # v1.0.8
        with:
          version: "0.9.3"

      - name: taplo fmt check
        shell: bash
        run: |
          taplo fmt --check
          taplo check

  run-tests:
    runs-on: depot-ubuntu-24.04-8
    strategy:
      matrix:
        version:
          - gateway: "0.42.1"
            cli: "0.98.0"
    env:
      RUSTFLAGS: -D warnings
    steps:
      - name: Get Sources
        uses: actions/checkout@v4

      - name: Start Docker Services
        shell: bash
        run: |
          docker compose up -d

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9

      - name: Install Rust
        uses: ./.github/actions/install-rust

      - name: Install Grafbase
        uses: ./.github/actions/install-grafbase
        with:
          gateway-version: ${{ matrix.version.gateway }}
          cli-version: ${{ matrix.version.cli }}

      - name: Install cargo-nextest
        uses: taiki-e/install-action@0eee80d37f55e834144deec670972c19e81a85b0 # v2.56.0
        with:
          tool: nextest

      - name: Install Protoc for the gRPC extension
        uses: arduino/setup-protoc@f4d5893b897028ff5739576ea0409746887fa536 # v3

      - name: Run Tests
        shell: bash
        env:
          RUSTC_WRAPPER: sccache
        run: |
          cargo run -p test-matrix
