name: pull-request

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-pull-request
  cancel-in-progress: true

jobs:
  check-format:
    runs-on: ubicloud-standard-2
    env:
      RUSTFLAGS: -D warnings
    steps:
      - name: Get Sources
        uses: actions/checkout@v4

      - name: Install Rust
        uses: ./.github/actions/install-rust
        with:
          components: clippy, rustfmt

      - name: cargo fmt
        shell: bash
        run: |
          cargo fmt --check

      - name: cargo clippy
        shell: bash
        run: |
          cargo clippy --locked

  run-tests:
    runs-on: ubicloud-standard-8
    strategy:
      matrix:
        version:
          - gateway: "0.29.0"
            sdk:
              - "0.8.0"
            cli: "0.86.1"
          - gateway: "0.30.2"
            sdk:
              - "0.8.0"
              - "0.9.0"
            cli: "0.87.2"
    env:
      RUSTFLAGS: -D warnings
    steps:
      - name: Get Sources
        uses: actions/checkout@v4

      - name: Start Docker Services
        shell: bash
        run: |
          docker compose up -d

      - name: Install Rust
        uses: ./.github/actions/install-rust

      - name: Install Grafbase
        uses: ./.github/actions/install-grafbase
        with:
          gateway-version: ${{ matrix.version.gateway }}
          cli-version: ${{ matrix.version.cli }}

      - name: Install cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - name: Run Tests
        shell: bash
        run: |
          cargo run -p test-matrix -- --sdk-version ${{ join(matrix.version.sdk, ' --sdk-version ') }}
